// packages/components/Bubble/Bubble.vue
<template>
  <div class="mc-bubble" :class="bubbleClasses">
    <div v-if="avatarConfig" class="mc-bubble-avatar" :class="{ 'empty-avatar': isEmptyAvatar }">
      <Avatar
        v-bind="
          isEmptyAvatar
            ? {
                width: avatarConfig?.width || DEFAULT_AVATAR_WIDTH,
                height: avatarConfig?.height || DEFAULT_AVATAR_HEIGHT,
              }
            : avatarConfig
        "
      ></Avatar>
      <span v-if="avatarPosition === 'top'" class="mc-bubble-avatar-name">{{ avatarConfig?.displayName }}</span>
    </div>
    <div class="mc-bubble-content-container" :class="{ 'with-avatar': avatarConfig }">
      <slot v-if="!loading" name="top"></slot>
      <div v-if="loading" class="loading-container">
        <slot name="loadingTpl">
          <BubbleLoading></BubbleLoading>
        </slot>
      </div>
      <div v-if="(slots.default || content) && !loading" class="mc-bubble-content" :class="[variant]">
        <slot>{{ content }}</slot>
      </div>
      <slot v-if="!loading" name="bottom"></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, useSlots } from 'vue';
import Avatar from './components/Avatar.vue';
import { props } from './bubble-types';
import { DEFAULT_AVATAR_WIDTH, DEFAULT_AVATAR_HEIGHT, AVATAR_NAME, AVATAR_IMG } from './bubble-constants';
import BubbleLoading from './BubbleLoading.vue';
import { BubbleFoundation } from '@matechat/common/Bubble/foundation';
import { useBubbleAdapter } from './adapter';

/**
 * top - 气泡顶部区域
 * loadingTpl - 自定义 Loading 样式
 * default - 内容区
 * bottom - 气泡底部区域
 */
const slots = useSlots();
const bubbleProps = defineProps(props);
const bubbleAdapter = useBubbleAdapter(bubbleProps);
const bubbleFoundation = new BubbleFoundation(bubbleAdapter);

const bubbleClasses = computed(() => {
  return bubbleFoundation.getBubbleClasses();
});

const isEmptyAvatar = computed(() => {
  return bubbleFoundation.getIsEmptyAvatar(bubbleProps.avatarConfig);
});
</script>

<style scoped lang="scss">
@import './bubble.scss';
</style>

// packages/components-ng/projects/components-ng/src/Bubble/bubble.component.ts
import { Component, Input, computed, ContentChild, TemplateRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BubbleLoadingComponent } from './bubble-loading/bubble-loading.component';
import { AvatarComponent } from './avatar/avatar.component';
import { DEFAULT_AVATAR_WIDTH, DEFAULT_AVATAR_HEIGHT, AVATAR_NAME, AVATAR_IMG } from '@matechat/common/Bubble/common/bubble-constants';
import { BubbleAlign, BubbleVariant, AvatarPosition, BubbleAvatar } from '@matechat/common/Bubble/common/bubble-types';
import { BubbleFoundation } from '@matechat/common/Bubble/foundation';

@Component({
  selector: 'mc-bubble',
  standalone: true,
  imports: [CommonModule, BubbleLoadingComponent, AvatarComponent],
  templateUrl: './bubble.component.html',
  styleUrls: ['./bubble.component.scss']
})
export class BubbleComponent {
  // 组件属性
  @Input() content: string = '';
  @Input() loading: boolean = false;
  @Input() align: BubbleAlign = 'left';
  @Input() avatarPosition: AvatarPosition = 'side';
  @Input() variant: BubbleVariant = 'filled';
  @Input() avatarConfig?: BubbleAvatar;

  // 内容投影模板引用
  @ContentChild('top') topTemplate: TemplateRef<any> | null = null;
  @ContentChild('loadingTpl') loadingTplTemplate: TemplateRef<any> | null = null;
  @ContentChild('defaultTemplate') defaultTemplate: TemplateRef<any> | null = null;
  @ContentChild('bottom') bottomTemplate: TemplateRef<any> | null = null;
  foundation: BubbleFoundation;

  constructor() { }

  ngOnInit() {
    this.foundation = new BubbleFoundation(this.adapter as any);
    this.foundation.init();
  }

  get adapter() {
    return {
      getProp: (key: string) => this,
      setState: (states: Record<string, any>, cb?: (...args: any) => void) => {
        Object.assign(this, states);
        cb && cb();
      },
      getState: (key: string) => this,
      getContext: (key: string) => this,
      getContexts: () => this,
      stopPropagation: (e: any) => {
        e.stopPropagation();
      },
    }
  }

  // 计算属性
  get bubbleClasses(): string {
    return this.foundation.bubbleClasses();
  };

  get isEmptyAvatar(): boolean {
    return this.foundation.isEmptyAvatar(this.avatarConfig);
  };
}

<div class="mc-bubble" [ngClass]="bubbleClasses">
  <div
    *ngIf="avatarConfig"
    class="mc-bubble-avatar"
    [ngClass]="{ 'empty-avatar': isEmptyAvatar }"
  >
    <mc-avatar
      *ngIf="!isEmptyAvatar"
      [imgSrc]="avatarConfig?.imgSrc || ''"
      [name]="avatarConfig?.name || ''"
      [width]="avatarConfig?.width || 36"
      [height]="avatarConfig?.height || 36"
      [gender]="avatarConfig?.gender || ''"
    />
    <div *ngIf="isEmptyAvatar" class="mc-bubble-avatar-wrapper" 
         [style.width.px]="avatarConfig?.width || 36"
         [style.height.px]="avatarConfig?.height || 36"></div>
    <span *ngIf="avatarPosition === 'top'" class="mc-bubble-avatar-name">{{
      avatarConfig?.displayName
    }}</span>
  </div>
  <div
    class="mc-bubble-content-container"
    [ngClass]="{ 'with-avatar': avatarConfig }"
  >
    <!-- 顶部内容投影 -->
    <ng-container *ngIf="!loading">
      <ng-container *ngTemplateOutlet="topTemplate"></ng-container>
      <ng-content select="[top]"></ng-content>
    </ng-container>
    
    <!-- 加载状态 -->
    <div *ngIf="loading" class="loading-container">
      <ng-container *ngIf="loadingTplTemplate; else defaultLoadingTemplate">
        <ng-container *ngTemplateOutlet="loadingTplTemplate"></ng-container>
        <ng-content select="[loadingTpl]"></ng-content>
      </ng-container>
      <ng-template #defaultLoadingTemplate>
        <mc-bubble-loading></mc-bubble-loading>
      </ng-template>
    </div>
    
    <!-- 主要内容 -->
    <div
      *ngIf="(defaultTemplate || content) && !loading"
      class="mc-bubble-content"
      [ngClass]="[variant]"
    >
      <ng-container *ngIf="defaultTemplate; else contentTemplate">
        <ng-container *ngTemplateOutlet="defaultTemplate"></ng-container>
        <ng-content></ng-content>
      </ng-container>
      <ng-template #contentTemplate>
        {{ content }}
      </ng-template>
    </div>
    
    <!-- 底部内容投影 -->
    <ng-container *ngIf="!loading">
      <ng-container *ngTemplateOutlet="bottomTemplate"></ng-container>
      <ng-content select="[bottom]"></ng-content>
    </ng-container>
  </div>
</div>
