// packages/components/Layout/Content.vue
<template>
  <div class="mc-layout-content-container">
    <div ref="scrollerRef" class="mc-layout-content-scroller">
      <div ref="contentRef" class="mc-layout-content">
        <slot></slot>
      </div>
    </div>
    <template v-if="showScrollArrow">
      <div v-if="showUpArrow" class="mc-layout-content-arrow up" @click="scrollToTop">
        <div>
          <i class="icon icon-arrow-up-l"></i>
        </div>
      </div>
      <div v-if="showDownArrow" class="mc-layout-content-arrow down" @click="scrollToBottom">
        <div>
          <i class="icon icon-arrow-down-l "></i>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { debounce } from 'lodash-es';
import { onMounted, onUnmounted, ref } from 'vue';
import type { ILayoutContentProps } from './layout-types';

const props = withDefaults(defineProps<ILayoutContentProps>(), {
  showScrollArrow: true,
  autoScroll: true,
});
const emits = defineEmits(['onScrollerWheel', 'onScrollerScroll']);
const scrollerRef = ref<HTMLDivElement>();
const contentRef = ref<HTMLDivElement>();
const showUpArrow = ref(false);
const showDownArrow = ref(false);
const contentResizeOb = new ResizeObserver(() => {
  updateScroll();
});

let userControl = false;

const scrollToPosition = (position: number) => {
  if (scrollerRef.value) {
    scrollerRef.value.scrollTo({ top: position, behavior: 'smooth' });
  }
};
const scrollToBottom = () => {
  scrollToPosition(scrollerRef.value?.scrollHeight || 0);
};
const scrollToTop = () => {
  scrollToPosition(0);
};

const updateScroll = (force = false) => {
  if (!props.autoScroll) {
    return;
  }
  if (userControl && !force) {
    return;
  }
  scrollToBottom();
};

const wheelHandler = (event: WheelEvent) => {
  if (!scrollerRef.value) {
    return;
  }
  const isBottom =
    Math.abs(
      scrollerRef.value.scrollTop +
        scrollerRef.value.clientHeight -
        scrollerRef.value.scrollHeight,
    ) < 32;
  if (event.deltaY !== 0) {
    userControl = !isBottom;
  }
  emits('onScrollerWheel', event);
};
const scrollHandler = debounce((event: Event) => {
  const target = event.target as HTMLDivElement;
  if (!target) {
    return;
  }
  showUpArrow.value = target.scrollTop !== 0;
  showDownArrow.value =
    target.scrollTop + target.clientHeight + 32 < target.scrollHeight;
  emits('onScrollerScroll', event);
}, 100);

const addScrollerEventListener = () => {
  scrollerRef.value?.addEventListener('scroll', scrollHandler);
  scrollerRef.value?.addEventListener('wheel', wheelHandler);
};
const removeScrollerEventListener = () => {
  scrollerRef.value?.removeEventListener('scroll', scrollHandler);
  scrollerRef.value?.removeEventListener('wheel', wheelHandler);
};

onMounted(() => {
  contentResizeOb.observe(contentRef.value!);
  addScrollerEventListener();
  scrollHandler({ target: scrollerRef.value } as any);
});
onUnmounted(() => {
  contentResizeOb.disconnect();
  removeScrollerEventListener();
});

defineExpose({
  scrollerRef,
  updateScroll,
  scrollToPosition,
  scrollToBottom,
  scrollToTop,
});
</script>

<style scoped lang="scss">
@import '@matechat/common/Layout/common/layout-content.scss';
</style>

// packages/components-ng/projects/components-ng/src/Layout/content/content.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  type ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
} from '@angular/core';
import { debounce } from 'lodash-es';
import BaseComponent from '../../Base/base.component';
import {
  type LayoutContentAdapter,
  LayoutContentFoundation,
} from '../../components-common/Layout/content-foundation';

@Component({
  selector: 'mc-layout-content',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './content.component.html',
  styleUrls: ['./content.component.scss'],
})
export class LayoutContentComponent extends BaseComponent<LayoutContentFoundation> {
  // 组件属性
  @Input() autoScroll: boolean = true;
  @Input() showScrollArrow: boolean = true;

  @Output() onScrollerScroll = new EventEmitter<Event>();
  @Output() onScrollerWheel = new EventEmitter<WheelEvent>();

  @ViewChild('scrollerRef') scrollerRef!: ElementRef;
  @ViewChild('contentRef') contentRef!: ElementRef;

  showUpArrow = false;
  showDownArrow = false;
  userControl = false;

  private contentResizeOb = new ResizeObserver(() => {
    this.updateScroll();
  });

  ngOnInit() {
    this.foundation = new LayoutContentFoundation(this.adapter);
    this.foundation.init();
  }
  ngAfterViewInit(): void {
    this.contentResizeOb.observe(this.contentRef.nativeElement);
    this.scrollHandler({ target: this.scrollerRef.nativeElement } as any);
    this.initListener();
  }
  override ngOnDestroy(): void {
    this.contentResizeOb.disconnect();
    this.removeListener();
    super.ngOnDestroy();
  }

  override get adapter(): LayoutContentAdapter {
    return {
      ...super.adapter,
      getProps: () => ({
        autoScroll: this.autoScroll,
        showScrollArrow: this.showScrollArrow,
      }),
    };
  }

  private wheelHandler = (event: WheelEvent) => {
    if (!this.scrollerRef.nativeElement) {
      return;
    }
    const isBottom =
      Math.abs(
        this.scrollerRef.nativeElement.scrollTop +
          this.scrollerRef.nativeElement.clientHeight -
          this.scrollerRef.nativeElement.scrollHeight,
      ) < 32;
    if (event.deltaY !== 0) {
      this.userControl = !isBottom;
    }
    this.onScrollerWheel.emit(event);
  };
  private scrollHandler = debounce((event: Event) => {
    const target = event.target as HTMLDivElement;
    if (!target) {
      return;
    }
    this.showUpArrow = target.scrollTop !== 0;
    this.showDownArrow =
      target.scrollTop + target.clientHeight + 32 < target.scrollHeight;
    this.onScrollerScroll.emit(event);
  }, 100);
  private initListener() {
    this.scrollerRef.nativeElement?.addEventListener(
      'scroll',
      this.scrollHandler,
    );
    this.scrollerRef.nativeElement?.addEventListener(
      'wheel',
      this.wheelHandler,
    );
  }
  private removeListener() {
    this.scrollerRef.nativeElement?.removeEventListener(
      'scroll',
      this.scrollHandler,
    );
    this.scrollerRef.nativeElement?.removeEventListener(
      'wheel',
      this.wheelHandler,
    );
  }

  scrollToPosition = (position: number) => {
    if (this.scrollerRef.nativeElement) {
      this.scrollerRef.nativeElement.scrollTo({
        top: position,
        behavior: 'smooth',
      });
    }
  };
  scrollToBottom = () => {
    this.scrollToPosition(this.scrollerRef.nativeElement?.scrollHeight ?? 0);
  };
  scrollToTop = () => {
    this.scrollToPosition(0);
  };
  updateScroll = (force = false) => {
    if (!this.autoScroll) {
      return;
    }
    if (this.userControl && !force) {
      return;
    }
    this.scrollToBottom();
  };
}

<div class="mc-layout-content-container">
  <div class="mc-layout-content-scroller" #scrollerRef>
    <div class="mc-layout-content" #contentRef>
      <ng-content></ng-content>
    </div>
  </div>
  <ng-container *ngIf="showScrollArrow">
    <div *ngIf="showUpArrow" class="mc-layout-content-arrow up" (click)="scrollToTop()">
      <div>
        <i class="icon icon-arrow-up-l"></i>
      </div>
    </div>
    <div *ngIf="showDownArrow" class="mc-layout-content-arrow down" (click)="scrollToBottom()">
      <div>
        <i class="icon icon-arrow-down-l "></i>
      </div>
    </div>
  </ng-container>
</div>
