// packages/components-ng/projects/components-ng/src/Introduction/introduction.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import BaseComponent from '../Base/base.component';
import type {
  IntroductionAlign,
  IntroductionBackground,
} from '../components-common/Introduction/common/introduction-types';
import { IntroductionFoundation } from '../components-common/Introduction/foundation';

@Component({
  selector: 'mc-introduction',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './introduction.component.html',
  styleUrls: ['./introduction.component.scss'],
})
export class IntroductionComponent extends BaseComponent<IntroductionFoundation> {
  @Input() logoImg?: string;
  @Input() title?: string;
  @Input() subTitle?: string;
  @Input() description: string[] = [];
  @Input() logoWidth?: number | string;
  @Input() logoHeight?: number | string;
  @Input() background: IntroductionBackground = 'transparent';
  @Input() align: IntroductionAlign = 'center';

  constructor() {
    super();
    this.foundation = new IntroductionFoundation(this.adapter);
  }
}

<div class="mc-introduction" [ngClass]="foundation.getIntroductionClasses()">
  <div class="mc-introduction-logo-container">
    <img *ngIf="logoImg" [src]="logoImg" [alt]="title" [ngStyle]="foundation.getLogoStyle()" />
    <div class="mc-introduction-title">{{ title }}</div>
  </div>
  <div *ngIf="subTitle" class="mc-introduction-sub-title">{{ subTitle }}</div>
  <div *ngIf="description && description.length" class="mc-introduction-description">
    <div *ngFor="let item of description; let i = index">{{ item }}</div>
  </div>
  <ng-content></ng-content>
</div>

// packages/components/Introduction/Introduction.vue
<template>
  <div class="mc-introduction" :class="foundation.getIntroductionClasses()">
    <div class="mc-introduction-logo-container">
      <img v-if="logoImg" :src="logoImg" :alt="title" :style="foundation.getLogoStyle()" />
      <div class="mc-introduction-title">{{ title }}</div>
    </div>
    <div v-if="subTitle" class="mc-introduction-sub-title">{{ subTitle }}</div>
    <div v-if="description.length" class="mc-introduction-description">
      <div v-for="(item, index) in description" :key="index">{{ item }}</div>
    </div>
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { IntroductionFoundation } from '@matechat/common/Introduction/foundation';
import { props } from './introduction-types';

const propsValue = defineProps(props);

const adapter = {
  getProp: (key: string) => {
    return propsValue[key as keyof typeof propsValue];
  },
  getProps: () => propsValue,
};

const foundation = new IntroductionFoundation(adapter as any);
</script>

<style scoped lang="scss">
@import '@matechat/common/Introduction/common/introduction.scss';
</style>
