// packages/components-svelte/components/Button/Button.svelte
<script>
  import { onMount } from "svelte";

  export let label = "Default Label"; // 按钮文本
  export let icon = ""; // 按钮图标类名
  export let size = "md"; // 按钮大小，支持 sm、md、lg
  export let loading = false; // 是否显示加载状态
  export let disabled = false; // 是否禁用按钮
  export let styleType = "border-gradient"; // 按钮样式类型
  export let shape = "capsule"; // 按钮形状，支持 capsule、round、circle
  export let width = ""; // 按钮宽度
  export let onClick = (e) => {}; // 点击事件处理函数
  export let slots = {
    icon: null,
    suffix: null,
  };

  let iconSlotContainer;
  let expandSlotContainer;

  const btnClick = (e) => {
    if (disabled) return;
    onClick(e);
  };

  onMount(() => {
    if (slots.suffix && expandSlotContainer) {
      expandSlotContainer.appendChild(slots.suffix);
    }
    if (slots.icon && iconSlotContainer) {
      iconSlotContainer.appendChild(slots.icon);
    }
  });
</script>

<div class="mc-button-wrapper">
  <button
    class="mc-button {disabled
      ? 'disabled'
      : ''} button-{styleType} mc-button--{size} mc-button--{shape} {slots.icon
      ? 'mc-button--suffix'
      : ''}"
    style={width ? `width: ${width};` : ""}
    on:click={btnClick}
  >
    {#if loading}
      <i class="loading-icon"></i>
    {/if}
    {#if icon}
      <i class="icon {icon}"></i>
    {/if}
    {#if slots.icon}
      <div class="icon-slot" bind:this={iconSlotContainer}></div>
    {/if}
    <slot>
      <span class="mc-button-content">{label}</span></slot
    >
    {#if slots.suffix}
      <div class="suffix-slot" bind:this={expandSlotContainer}></div>
    {/if}
  </button>
</div>

<style lang="scss">
  @import "@devui-design/icons/icomoon/devui-icon.css";
  @import "devui-theme/styles-var/devui-var.scss";

  $button-size: (
    sm: 26px,
    md: 30px,
    lg: 38px,
  );
  $button-gradient-bg: linear-gradient(
    90deg,
    #93d6f9,
    #abee88,
    #fdc68d,
    #fa9d8e,
    #f48ae1
  );
  $button-padding: 0 13px;

  @each $size, $value in $button-size {
    .mc-button--#{$size} {
      height: $value;
      margin: 1px;
    }
  }

  .mc-button-wrapper {
    position: relative;
    z-index: 0;
  }

  .mc-button {
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;
    height: map-get($button-size, md);
    padding: $button-padding;
    color: $devui-text;
    border: none;
    border-radius: 100px;
    white-space: nowrap;
    cursor: pointer;

    .icon,
    .icon-slot {
      margin-right: 4px;
    }

    &.disabled {
      color: $devui-disabled-text;
      cursor: not-allowed;
    }
  }

  .button-border-gradient {
    color: $devui-text;
    background-color: $devui-base-bg;
    &::after {
      content: "";
      position: absolute;
      top: -1px;
      left: -1px;
      right: -1px;
      bottom: -1px;
      border-radius: 100px;
      background: $button-gradient-bg;
      z-index: -1;
    }

    &::before {
      content: "";
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      border-radius: 100px;
      background: $button-gradient-bg;
      filter: blur(4px);
      z-index: -1;
    }
  }

  .mc-button--suffix {
    padding-left: 11px;
  }

  .mc-button--sm {
    height: map-get($button-size, sm);
    font-size: 12px;
  }
  .mc-button--md {
    height: map-get($button-size, md);
    font-size: 14px;
  }
  .mc-button--lg {
    height: map-get($button-size, lg);
    font-size: 16px;
  }

  .mc-button--capsule {
    border-radius: 100px;
  }

  .mc-button--circle {
    border-radius: 50%;

    &.mc-button--sm {
      width: map-get($button-size, sm);
    }
    &.mc-button--md {
      width: map-get($button-size, md);
    }
    &.mc-button--lg {
      width: map-get($button-size, lg);
    }
  }
</style>

// packages/components/Input/components/button.vue
<template>
  <button
    :disabled="rootProps.disabled || (!rootProps.loading && !inputValue)"
    :class="buttonClasses"
    @click="onConfirm"
    @mousedown="() => (isMouseDown = true)"
    @mouseup="() => (isMouseDown = false)"
  >
    <span class="mc-button-content">
      <LoadingIcon v-if="rootProps.loading" />
      <SendIcon v-else />
      <span v-if="rootProps.sendBtnVariant === SendBtnVariant.Full">
        {{ rootProps.loading ? t("Input.pauseAnswer") : t("Input.send") }}
      </span>
    </span>
    <div v-if="showWave" class="mc-button-water-wave" :style="waveStyle"></div>
  </button>
</template>

<script setup lang="ts">
import { inject, ref, reactive, computed } from "vue";
import LoadingIcon from "./LoadingIcon.vue";
import SendIcon from "./SendIcon.vue";
import { inputInjectionKey, SendBtnVariant } from "../input-types";
import type { InputContext } from "../input-types";
import { useMcI18n } from "@matechat/core/Locale";

const { t } = useMcI18n();

const { inputValue, rootProps, rootEmits } = inject(
  inputInjectionKey
) as InputContext;
const isMouseDown = ref(false);
const showWave = ref(false);
const waveStyle = reactive({
  top: "0px",
  left: "0px",
});
const buttonClasses = computed(() => ({
  "mc-button": true,
  "mc-button-loading": rootProps.loading,
  mousedown: isMouseDown.value,
  "mc-button-simple": rootProps.sendBtnVariant === SendBtnVariant.Simple,
}));

const showClickWave = (e: MouseEvent) => {
  waveStyle.left = e.offsetX + "px";
  waveStyle.top = e.offsetY + "px";
  showWave.value = true;

  setTimeout(() => {
    showWave.value = false;
  }, 300);
};

const onConfirm = (e: MouseEvent) => {
  showClickWave(e);
  if (rootProps.loading) {
    rootEmits("cancel");
  } else {
    rootEmits("submit", inputValue.value);
    inputValue.value = "";
    rootEmits('change', inputValue.value);
  }
};
</script>

<style scoped lang="scss">
@import "devui-theme/styles-var/devui-var.scss";

.mc-button {
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  white-space: nowrap;
  height: 32px;
  line-height: 1.5;
  color: $devui-light-text;
  font-size: var(--devui-font-size, 14px);
  padding: 0 12px;
  border-radius: 20px;
  background-color: $devui-primary;
  overflow: hidden;
  border: none;
  cursor: pointer;
  transition: background-color $devui-animation-duration-slow
      $devui-animation-ease-in-out-smooth,
    border-color $devui-animation-duration-slow
      $devui-animation-ease-in-out-smooth,
    color $devui-animation-duration-slow $devui-animation-ease-in-out-smooth;

  &.mc-button-loading {
    svg {
      animation: rotating 1s linear infinite;
    }
  }

  &.mousedown:not(:disabled) {
    transform: scale(0.95);
  }

  &.mc-button-simple {
    width: 32px;
    padding: 6px;
    flex-shrink: 0;
    border-radius: 100%;

    svg {
      margin-right: 0;
    }
  }

  &:hover {
    background-color: $devui-primary-hover;
  }
  &:active {
    background-color: $devui-primary-active;
  }
  &:disabled {
    color: $devui-light-text;
    background-color: $devui-primary-disabled;
    cursor: not-allowed;
  }

  .mc-button-content {
    display: inline-flex;
    align-items: center;
    font-size: var(--devui-font-size, 14px);
  }

  .mc-button-water-wave {
    position: absolute;
    background-color: $devui-base-bg;
    border-radius: 50%;
    opacity: 0;
    width: 20px;
    height: 20px;
    transform: translate(-50%, -50%);
    animation: waterWave $devui-animation-duration-slow $devui-animation-linear;
  }

  svg {
    :deep(path) {
      fill: $devui-light-text;
    }
    margin-right: 4px;
  }
}

@keyframes rotating {
  0% {
    transform: rotate(0);
  }

  100% {
    transform: rotate(180deg);
  }
}

@keyframes waterWave {
  0% {
    opacity: 0.2;
    width: 30px;
    height: 30px;
  }

  100% {
    opacity: 0;
    width: 200px;
    height: 200px;
  }
}
</style>
