// packages/components-ng/projects/components-ng/src/Input/button/button.component.ts
import { Component, Input, EventEmitter, Output, HostListener, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SendIconComponent } from '../send-icon/send-icon.component';
import { SendBtnVariant } from '../../components-common/Input/common/types';
import BaseComponent from '../../Base/base.component';
import { LocaleService, TranslatePipe } from '../../components-common/Locale';
import { InputButtonAdapter, InputButtonFoundation } from '../../components-common/Input/button-foundation';

@Component({
  selector: 'mc-button',
  standalone: true,
  imports: [CommonModule, SendIconComponent, TranslatePipe],
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss'],
})export class ButtonComponent extends BaseComponent {
  @Input() disabled: boolean = false;
  @Input() loading: boolean = false;
  @Input() inputValue: string = '';
  @Input() sendBtnVariant: SendBtnVariant = SendBtnVariant.Full;
  
  @Output() submit = new EventEmitter<string>();
  @Output() cancel = new EventEmitter<void>();
  @Output() change = new EventEmitter<string>();
  
  @ViewChild('button') buttonElement!: ElementRef<HTMLButtonElement>;
  
  isMouseDown: boolean = false;
  showWave: boolean = false;
  waveStyle: { top: string; left: string } = { top: '0px', left: '0px' };
  
  constructor(private localeService: LocaleService) { super(); }
  
  get buttonClasses(): string {
    return this.foundation.getButtonClasses();
  }
  
  ngOnInit() {
    this.foundation = new InputButtonFoundation(this.adapter as InputButtonAdapter);
    this.foundation.init();
  }
  
  @HostListener('mousedown')
  onMouseDown(): void {
    this.isMouseDown = true;
  }
  
  @HostListener('mouseup')
  onMouseUp(): void {
    this.isMouseDown = false;
  }
  
  showClickWave(event: MouseEvent): void {
    this.foundation.showClickWave(this.buttonElement.nativeElement, event);
  }
  
  onConfirm(event: MouseEvent): void {
    this.showClickWave(event);
    
    if (this.loading) {
      this.cancel.emit();
    } else {
      this.submit.emit(this.inputValue);
      this.inputValue = '';
      this.change.emit(this.inputValue);
    }
  }
  

}

// packages/components/Input/components/button.vue
<template>
  <button
    :disabled="rootProps.disabled || (!rootProps.loading && !inputValue)"
    :class="buttonClasses"
    @click="onConfirm"
    @mousedown="() => (isMouseDown = true)"
    @mouseup="() => (isMouseDown = false)"
  >
    <span class="mc-button-content">
      <LoadingIcon v-if="rootProps.loading" />
      <SendIcon v-else />
      <span v-if="rootProps.sendBtnVariant === SendBtnVariant.Full">
        {{ rootProps.loading ? t("Input.pauseAnswer") : t("Input.send") }}
      </span>
    </span>
    <div v-if="showWave" class="mc-button-water-wave" :style="waveStyle"></div>
  </button>
</template>

<script setup lang="ts">
import { inject, ref, reactive, computed } from "vue";
import LoadingIcon from "./LoadingIcon.vue";
import SendIcon from "./SendIcon.vue";
import { inputInjectionKey, SendBtnVariant } from "../input-types";
import type { InputContext } from "../input-types";
import { useMcI18n } from "@matechat/core/Locale";

const { t } = useMcI18n();

const { inputValue, rootProps, rootEmits } = inject(
  inputInjectionKey
) as InputContext;
const isMouseDown = ref(false);
const showWave = ref(false);
const waveStyle = reactive({
  top: "0px",
  left: "0px",
});
const buttonClasses = computed(() => ({
  "mc-button": true,
  "mc-button-loading": rootProps.loading,
  mousedown: isMouseDown.value,
  "mc-button-simple": rootProps.sendBtnVariant === SendBtnVariant.Simple,
}));

const showClickWave = (e: MouseEvent) => {
  waveStyle.left = e.offsetX + "px";
  waveStyle.top = e.offsetY + "px";
  showWave.value = true;

  setTimeout(() => {
    showWave.value = false;
  }, 300);
};

const onConfirm = (e: MouseEvent) => {
  showClickWave(e);
  if (rootProps.loading) {
    rootEmits("cancel");
  } else {
    rootEmits("submit", inputValue.value);
    inputValue.value = "";
    rootEmits('change', inputValue.value);
  }
};
</script>

<style scoped lang="scss">
@import '@matechat/common/Base/vue.scss';
@import '@matechat/common/Input/common/button.scss';
</style>
