// packages/components-ng/projects/components-ng/src/Input/EditableBlock/editable-block.component.ts
import { Component, Input, EventEmitter, Output, ViewChild, ElementRef, SimpleChanges, ContentChild, TemplateRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import BaseComponent from '../../Base/base.component';
import { LocaleService } from '../../Locale';

import { handlePaste, insertText, moveCursorToTextEnd } from '../../components-common/Input/common/util';
import { InputTagFoundation } from '../../components-common/Input/input-tag-foundation';
import { InputTagComponent } from '../InputTag/input-tag.component';
import { DisplayType, FormatContentItem, SubmitShortKey, ThemeTagItem, TimeToViewRender } from '../../components-common/Input/common/types';
// import { PopoverModule } from 'ng-devui/popover';

@Component({
  selector: 'mc-editable-block',
  standalone: true,
  imports: [CommonModule, InputTagComponent],
  templateUrl: './editable-block.component.html',
  styleUrls: ['./editable-block.component.scss'],
})export class EditableBlockComponent extends BaseComponent<InputTagFoundation> {

  themeTag: ThemeTagItem = {
    themeTagText: '',
    clearInput: false,
    popoverContent: '',
    type: 'themeTag',
  };
  
  @Input() disabled: boolean = false;
  @Input() displayType: DisplayType = DisplayType.Simple;
  @Input() placeholder: string = '';

  @Input() templateParts: any[] = [];
  @Input() maxLength: number | null = 2000;
  @Input() submitShortKey: SubmitShortKey | null | string =
      SubmitShortKey.Enter;
  @Input() autofocus: boolean = false;

  @Output() send = new EventEmitter<string>();
  @Output() input = new EventEmitter<string>();
  @Output() blur = new EventEmitter<FocusEvent>();
  @Output() focus = new EventEmitter<FocusEvent>();
  @Output() onBlockKeyArrowUp = new EventEmitter<KeyboardEvent>();
  @ViewChild('editableDivRef') editableDivRef!: ElementRef<HTMLDivElement>;
  @ContentChild('themeTag') themeTagTemplate: TemplateRef<any> | null = null;
  localTemplateParts: any = [...this.templateParts];

  constructor(private localeService: LocaleService) { super(); }
  
  ngOnChanges(changes: SimpleChanges) {
    if (changes['templateParts']) {
      this.localTemplateParts = [...changes['templateParts'].currentValue];
    }
  }

  ngOnInit() {
    if (this.autofocus && this.editableDivRef?.nativeElement && !this.disabled) {
      this.onFocusInput();
    }
  }

  clearInput() {
    const inputWarp = this.editableDivRef?.nativeElement;
    if (inputWarp) {
      inputWarp.innerHTML = '';
      this.handleDivInput();
    }
  }

  getInput(){
    return this.getCurrentInputValue();
  }

  handleSend() {
    const prompt = (this.editableDivRef?.nativeElement as any)?.textContent;
    if (this.maxLength && prompt.length > this.maxLength) {
      return;
    }
    this.send.emit(prompt);
    this.clearInput();
  }

  focusInput() {
    this.editableDivRef?.nativeElement.focus();
    moveCursorToTextEnd(this.editableDivRef?.nativeElement);
  }

  onFocus($event: FocusEvent) {
    this.focus.emit($event);
  }
  onBlur($event: FocusEvent) {
    this.blur.emit($event);
  }

  isComposing: boolean = false;

  handleCompositionEnd($event: CompositionEvent) {
    this.isComposing = false;
    this.handleDivInput();
  }
  handleCompositionStart($event: CompositionEvent) {
    this.isComposing = true;
  }
  handleDivPaste(e: any) {
    e.preventDefault();
    const text = (e.originalEvent || e).clipboardData?.getData('text/plain');
    insertText(text);
    this.handleDivInput();
  }
  handleDivKeydown(e: KeyboardEvent) {
    const shiftKey = this.submitShortKey === SubmitShortKey.Enter ? !e.shiftKey : this.submitShortKey === SubmitShortKey.ShiftEnter ? e.shiftKey : false;
    if (e.key === 'Enter' && shiftKey) {
      e.preventDefault();
      this.handleSend();
    }
    if(['ArrowLeft', 'ArrowRight','Backspace','Delete'].includes(e.key)){
      const selection = window.getSelection();
      if (!selection?.rangeCount || !selection.isCollapsed) {
        return
      }

      const range = selection.getRangeAt(0);
      const { startContainer: node, startOffset} = range;
      const direction = e.key === 'ArrowLeft' || e.key === 'Backspace' ? 'previous': 'next';
      const targetNode: any = this.findSiblingNode(node, startOffset, direction);
      if(targetNode && targetNode.nodeType === Node.ELEMENT_NODE){
        const editSpanDom = targetNode.querySelector('.input-custom-item');
        if(!editSpanDom){
          return;
        }
        e.preventDefault();
        editSpanDom.contentEditable = 'true';
        if(e.key === 'ArrowLeft' || e.key === 'ArrowRight'){
          const newRange = document.createRange();

          newRange.setStart(editSpanDom, direction === 'previous' ? editSpanDom.childNodes.length : 0);
          newRange.collapse(false);
          selection.removeAllRanges();
          selection.addRange(newRange);
        }else if(e.key === 'Backspace' || e.key === 'Delete'){
          if(editSpanDom.textContent.trim()){
            const newRange = document.createRange();
            newRange.setStart(editSpanDom, direction === 'previous' ? editSpanDom.childNodes.length : 0);
            newRange.collapse(false);
            selection.removeAllRanges();
            selection.addRange(newRange);

          }else{
            targetNode.remove();
          }
        }
      }
    }
    if(e.key === 'ArrowUp'){
      this.isCursorAtStart() ? this.onBlockKeyArrowUp.emit(e) : null;
    }
  }

  isCursorAtStart(){
    const selection = window.getSelection();
    if (!selection?.rangeCount) {
      return true;
    }
    const range = selection.getRangeAt(0);
    if(range.startOffset !== 0){
      return false;
    }
    let node :any= range.startContainer;
    while(node && !node.classList?.contains('editable-container')){
      if(node.previousSibling){
        return false;
      }
      node = node.parentNode;
    }
    return true;
  }

  findSiblingNode(node:any, startOffset: number, direction: 'previous' | 'next'){
    if(!node){
      return null;
    }

    let current = node;
    const isEditableContainer = node.classList?.contains('editable-container');
    if(isEditableContainer){
      const childNodes = node.childNodes;
      const index = Math.min(startOffset, childNodes.length - 1);
      current = childNodes[index];
    }
    if(!isEditableContainer && direction === 'previous' &&startOffset !== 0){
      return null;
    }
    if(!isEditableContainer && direction === 'next' && startOffset !== node.textContent.length){
      return null;
    }
    let target = null;
    let sibling = current;
    while(sibling){
      sibling = direction === 'next' ? sibling.nextSibling : sibling.previousSibling;
      if(!sibling){
        continue;
      }
      // 排除注释节点和值为空的文本节点
      if(sibling.nodeType !== Node.COMMENT_NODE && (sibling.nodeType !== Node.TEXT_NODE || (sibling.nodeType === Node.TEXT_NODE && sibling.nodeValue.trim() !== ''))){
        target = sibling;
        break;
      }
      
    }
    return target;
  }


  handleDivInput() {
    if(!this.isComposing) {
      this.processInput();
    }
  }

  getCurrentInputValue() {
    let prompt = (this.editableDivRef?.nativeElement as any)?.textContent;
    // 前置标签TipTag的文本需要去除掉
    if(this.themeTag.themeTagText){
      const prefixSpan = this.editableDivRef?.nativeElement?.querySelector('.ai-input-prefix-wrapper');
      if(prefixSpan){
        prompt = prompt.replace(prefixSpan.textContent || '', ' ');
      }
    }
    return prompt;
  }

  processInput() {
    setTimeout(() => {
      const prompt = this.getCurrentInputValue();
      this.input.emit(prompt);
    }, TimeToViewRender);
  }

  setInputTag(key: string, placeholder: string, defaultValue?: string) {
    if(this.disabled) {
      return;
    }
    this.localTemplateParts.push({
      key,
      type: 'input',
      placeholder,
      content: defaultValue,
    });
    this.onFocusInput();
    this.handleDivInput();
  }
  
  setMixTags(mixTagConfig:FormatContentItem[]) {
    if(this.disabled) {
      return;
    }
    this.localTemplateParts = [...mixTagConfig];
    this.onFocusInput();
    this.handleDivInput();
  }

  setText(text:string) {
    if(this.disabled) {
      return;
    }
    this.localTemplateParts.push({
      key: 'text',
      type: 'text',
      content: text,
    });
    this.onFocusInput();
    this.handleDivInput();
  }
  
  openTipTag(themeTagText:string, popoverContent:string, clearInput?: boolean){
    if(this.disabled) {
      return;
    }
    this.themeTag = {
      themeTagText,
      popoverContent,
      clearInput: clearInput || false,
      type: 'themeTag'
    };

  }
 
  closeTipTag() {
    if(this.themeTag.themeTagText && this.themeTag.clearInput){
      this.clearInput();
    }else{
      this.themeTag = {
        themeTagText: '',
        popoverContent: '',
        clearInput: false,
        type: 'themeTag'
      };
      this.processInput();
    }
  }

  onFocusInput() {
    this.focusInput();
  }

}
  <div 
    #editableDivRef
    class="editable-container"
    [ngClass]="{'mc-input-disabled': disabled,'mc-input-simple': displayType === 'simple' }"
    [attr.contenteditable]="!disabled"
    spellcheck="false"
    [attr.placeholder]="placeholder"
    (input)="handleDivInput()"
    (keydown)="handleDivKeydown($event)"
    (paste)="handleDivPaste($event)"
    (compositionstart)="handleCompositionStart($event)"
    (compositionend)="handleCompositionEnd($event)"
    (blur)="onBlur($event)"
    (focus)="onFocus($event)"
  >
    <!-- 前置标签 -->
    <!-- popover最后再实现打通 -->
    <!-- <span contenteditable="false" dPopover [content]="themeTag.popoverContent" trigger="hover" controlled = "true"> -->
    <span *ngIf="themeTag.themeTagText" contenteditable="false" >
      <span *ngIf="themeTag.themeTagText" [title]="themeTag.popoverContent" class="ai-input-prefix-wrapper" (click)="closeTipTag()" contenteditable="false">
        <ng-container *ngIf="themeTagTemplate">
          <ng-container *ngTemplateOutlet="themeTagTemplate; context: {$implicit: themeTag, themeTagText: themeTag.themeTagText}"></ng-container>
        </ng-container>
      </span>
      <span contenteditable="false" style="display: inline-block;width: 4px;"></span>
    </span>

    <ng-container *ngFor="let part of localTemplateParts" [ngSwitch]="part.type">
      <ng-container *ngSwitchCase="'text'">{{part.content}}</ng-container>
      <mc-input-tag *ngSwitchCase="'input'"  [content]="part.content" [placeholder]="part.placeholder" [disabled]="disabled" (change)="handleDivInput()"></mc-input-tag>
    </ng-container>
  </div>

// packages/components/Input/components/EditableBlock.vue
<template>
  <div 
    ref="editableDivRef"
    class="editable-container"
    :class="{'mc-input-disabled': props.disabled,'mc-input-simple': rootProps.displayType === DisplayType.Simple }"
    :contenteditable="!props.disabled"
    spellcheck="false"
    :placeholder="props.placeholder"
    @input="handleDivInput"
    @keydown="handleDivKeydown"
    @paste="handleDivPaste"
    @compositionstart="handleCompositionStart"
    @compositionend="handleCompositionEnd"
    @blur="onBlur"
    @focus="onFocus"
  >
    <!-- 前置标签 -->
    <d-popover v-if="themeTag.themeTagText " trigger="hover" :content="themeTag.popoverContent">
      <span contenteditable="false">
        <span v-if="themeTag.themeTagText" class="ai-input-prefix-wrapper" @click="closeTipTag" contenteditable="false">
          <slot name="themeTag" :themeTag="themeTag">
            <span id="ai-input-prefix" class="ai-input-prefix">{{themeTag.themeTagText}}</span>
          </slot>
        </span>
        <span contenteditable="false" style="display: inline-block;width: 4px;"></span>
      </span>
    </d-popover>
    <template v-for="(part, index) in localTemplateParts">
      <template v-if="part.type === 'text'">
        {{ part.content }}
      </template>
      <InputTag v-else-if="part.type === 'input'" :key="`input${index}`" :content="part.content" :placeholder="part.placeholder" :disabled="props.disabled" @change="handleDivInput"/>

    </template>
  </div>
</template>

<script setup lang="ts">
import { inject, nextTick, onMounted, type PropType, ref, watch } from 'vue';
import {
  DisplayType,
  type FormatContentItem,
  type InputContext,
  inputInjectionKey,
  SubmitShortKey,
  type ThemeTagItem,
} from '../input-types';
import InputTag from './InputTag.vue';
import { insertText, moveCursorToTextEnd } from './util';

const { rootProps } = inject(inputInjectionKey) as InputContext;
const emits = defineEmits([
  'send',
  'input',
  'blur',
  'focus',
  'onBlockKeyArrowUp',
]);
const props = defineProps({
  templateParts: {
    type: Array,
    default: () => [],
  },
  placeholder: {
    type: String,
    default: '',
  },
  maxLength: {
    type: Number,
    default: 2000,
  },
  disabled: {
    type: Boolean,
    default: false,
  },
  submitShortKey: {
    type: [String, null] as PropType<SubmitShortKey | null>,
    default: SubmitShortKey.Enter,
  },
  autofocus: {
    type: Boolean,
    default: false,
  },
});

const themeTag = ref<ThemeTagItem>({
  themeTagText: '',
  clearInput: false,
  popoverContent: '',
  type: 'themeTag',
});

const editableDivRef: any = ref(null);
const localTemplateParts: any = ref([...props.templateParts]);
watch(
  () => props.templateParts,
  (newParts) => {
    localTemplateParts.value = [...newParts];
  },
);

const clearInput = () => {
  const inputWarp = editableDivRef.value;
  if (inputWarp) {
    inputWarp.innerHTML = '';
    handleDivInput();
  }
};

const setInput = (text: string) => {
  const inputWarp = editableDivRef.value;
  if (inputWarp) {
    inputWarp.innerHTML = '';
    inputWarp.textContent = text;
    inputWarp.focus();
    moveCursorToTextEnd(inputWarp);
  }
};

const handleSend = () => {
  const prompt = (editableDivRef.value as any)?.textContent;
  if (prompt.length > props.maxLength) {
    return;
  }
  emits('send', prompt);
  clearInput();
};

const focusInput = () => {
  editableDivRef.value?.focus();
  moveCursorToTextEnd(editableDivRef.value);
};

const onBlur = (e: FocusEvent) => {
  emits('blur', e);
};

const onFocus = (e: FocusEvent) => {
  emits('focus', e);
};

const isComposing = ref(false);
const handleCompositionStart = () => {
  isComposing.value = true;
};

const handleCompositionEnd = () => {
  isComposing.value = false;
  handleDivInput();
};

const handleDivInput = () => {
  if (!isComposing.value) {
    processInput();
  }
};

const getCurrentInputValue = () => {
  let prompt = (editableDivRef.value as any)?.textContent;
  // 前置标签TipTag的文本需要去除掉
  if (themeTag.value.themeTagText) {
    const prefixSpan = editableDivRef.value?.querySelector(
      '.ai-input-prefix-wrapper',
    );
    if (prefixSpan) {
      const prefixText = prefixSpan.textContent || '';
      prompt = prompt.replace(prefixText, ' ');
    }
  }
  return prompt;
};

const processInput = () => {
  setTimeout(() => {
    const prompt = getCurrentInputValue();
    emits('input', prompt);
  }, 50);
};

const handleDivKeydown = (e: KeyboardEvent) => {
  const shiftKey =
    props.submitShortKey === SubmitShortKey.Enter
      ? !e.shiftKey
      : props.submitShortKey === SubmitShortKey.ShiftEnter
        ? e.shiftKey
        : false;
  if (e.key === 'Enter' && shiftKey) {
    e.preventDefault();
    handleSend();
  }
  if (['ArrowLeft', 'ArrowRight', 'Backspace', 'Delete'].includes(e.key)) {
    const selection = window.getSelection();
    if (!selection?.rangeCount || !selection.isCollapsed) {
      return;
    }

    const range = selection.getRangeAt(0);
    const { startContainer: node, startOffset } = range;
    const direction =
      e.key === 'ArrowLeft' || e.key === 'Backspace' ? 'previous' : 'next';
    const targetNode = findSiblingNode(node, startOffset, direction);
    if (targetNode && targetNode.nodeType === Node.ELEMENT_NODE) {
      const editSpanDom = targetNode.querySelector('.input-custom-item');
      if (!editSpanDom) {
        return;
      }
      e.preventDefault();
      editSpanDom.contentEditable = 'true';
      if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
        const newRange = document.createRange();

        newRange.setStart(
          editSpanDom,
          direction === 'previous' ? editSpanDom.childNodes.length : 0,
        );
        newRange.collapse(false);
        selection.removeAllRanges();
        selection.addRange(newRange);
      } else if (e.key === 'Backspace' || e.key === 'Delete') {
        if (editSpanDom.textContent.trim()) {
          const newRange = document.createRange();
          newRange.setStart(
            editSpanDom,
            direction === 'previous' ? editSpanDom.childNodes.length : 0,
          );
          newRange.collapse(false);
          selection.removeAllRanges();
          selection.addRange(newRange);
        } else {
          targetNode.remove();
        }
      }
    }
  }
  if (e.key === 'ArrowUp') {
    isCursorAtStart() ? emits('onBlockKeyArrowUp', e) : null;
  }
};

function isCursorAtStart() {
  const selection = window.getSelection();
  if (!selection?.rangeCount) {
    return true;
  }
  const range = selection.getRangeAt(0);
  if (range.startOffset !== 0) {
    return false;
  }
  let node: any = range.startContainer;
  while (node && !node.classList?.contains('editable-container')) {
    if (node.previousSibling) {
      return false;
    }
    node = node.parentNode;
  }
  return true;
}

function findSiblingNode(
  node: any,
  startOffset: number,
  direction: 'previous' | 'next',
) {
  if (!node) {
    return null;
  }

  let current = node;
  const isEditableContainer = node.classList?.contains('editable-container');
  if (isEditableContainer) {
    const childNodes = node.childNodes;
    const index = Math.min(startOffset, childNodes.length - 1);
    current = childNodes[index];
  }
  if (!isEditableContainer && direction === 'previous' && startOffset !== 0) {
    return null;
  }
  if (
    !isEditableContainer &&
    direction === 'next' &&
    startOffset !== node.textContent.length
  ) {
    return null;
  }
  let target = null;
  let sibling = current;
  while (sibling) {
    sibling =
      direction === 'next' ? sibling.nextSibling : sibling.previousSibling;
    if (!sibling) {
      continue;
    }
    // 排除注释节点和值为空的文本节点
    if (
      sibling.nodeType !== Node.COMMENT_NODE &&
      (sibling.nodeType !== Node.TEXT_NODE ||
        (sibling.nodeType === Node.TEXT_NODE &&
          sibling.nodeValue.trim() !== ''))
    ) {
      target = sibling;
      break;
    }
  }
  return target;
}

const handleDivPaste = (e: any) => {
  e.preventDefault();
  const text = (e.originalEvent || e).clipboardData?.getData('text/plain');
  insertText(text);
  handleDivInput();
};

const setInputTag = (
  key: string,
  placeholder: string,
  defaultValue?: string,
) => {
  if (props.disabled) {
    return;
  }
  localTemplateParts.value.push({
    key,
    type: 'input',
    placeholder,
    content: defaultValue,
  });
  onFocusInput();
  handleDivInput();
};

const setMixTags = (mixTagConfig: FormatContentItem[]) => {
  if (props.disabled) {
    return;
  }
  localTemplateParts.value = [...mixTagConfig];
  onFocusInput();
  handleDivInput();
};

const setText = (text: string) => {
  if (props.disabled) {
    return;
  }
  localTemplateParts.value.push({
    type: 'text',
    content: text,
  });
  onFocusInput();
  handleDivInput();
};

const openTipTag = (
  themeTagText: string,
  popoverContent: string,
  clearInput?: boolean,
) => {
  if (props.disabled) {
    return;
  }
  themeTag.value = {
    themeTagText,
    clearInput: clearInput || false,
    popoverContent,
    type: 'themeTag',
  };
};

const closeTipTag = () => {
  if (themeTag.value.themeTagText && themeTag.value.clearInput) {
    clearInput();
  } else {
    themeTag.value = {
      themeTagText: '',
      clearInput: false,
      popoverContent: '',
      type: 'themeTag',
    };
    processInput();
  }
};

const onFocusInput = () => {
  nextTick(() => {
    focusInput();
  });
};

onMounted(() => {
  if (props.autofocus && editableDivRef.value && !props.disabled) {
    onFocusInput();
  }
});

defineExpose({
  clearInput,
  getInput: getCurrentInputValue,
  focusInput,
  setMixTags,
  setText,
  setInputTag,
  openTipTag,
  closeTipTag,
});
</script>

<style scoped lang="scss">
@import "@matechat/common/Input/common/editable-block.scss";

</style>
