// packages/components-ng/projects/components-ng/src/Input/InputTag/input-tag.component.ts
import { Component, Input, EventEmitter, Output, ViewChild, ElementRef, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import BaseComponent from '../../Base/base.component';
import { LocaleService } from '../../Locale';

import { handlePaste } from '../../components-common/Input/common/util';
import { InputTagFoundation } from '../../components-common/Input/input-tag-foundation';


@Component({
  selector: 'mc-input-tag',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './input-tag.component.html',
  styleUrls: ['./input-tag.component.scss'],
})export class InputTagComponent extends BaseComponent<InputTagFoundation> {
  @Input() disabled: boolean = false;
  @Input() content: string = '';
  @Input() placeholder: string = '';
  @Output() change = new EventEmitter<string>();
  @ViewChild('editableSpanRef') editableSpanRef!: ElementRef<HTMLSpanElement>;
  
  isEditable: boolean = false;
  localValue: string = this.content;

  constructor(private localeService: LocaleService) { super(); }
  
  ngOnChanges(changes: SimpleChanges) {
    if (changes['content']) {
      this.localValue = changes['content'].currentValue;
    }
  }

  handleFocus() {
    this.isEditable = !this.disabled;
  }

  handleBlur() {
    this.isEditable = false;
  }

  handleInput(e: any) {
    const prompt = this.editableSpanRef?.nativeElement.textContent || '';
    this.localValue = prompt;
    this.change.emit(prompt);
  }

  handleInputPaste(e: any) {
    handlePaste(e);
    this.handleInput(e);
  }
}
<span class="editable-span" contenteditable="false">
  <span 
    #editableSpanRef
    [attr.contenteditable]="isEditable"
    [attr.placeholder]="placeholder"
    tabindex="0"
    class="input-custom-item"
    [ngClass]="{'input-custom-placeholder': !localValue?.length, 'inline-text': localValue?.length}"
    (input)="handleInput($event)"
    (focus)="handleFocus()"
    (blur)="handleBlur()"
    (paste)="handleInputPaste($event)"
  >{{content}}</span>
</span>

// packages/components/Input/components/InputTag.vue
<template>
  <span class="editable-span" contenteditable="false">
    <span 
      ref="editableSpanRef"
      :contenteditable="isEditable"
      :placeholder="placeholder"
      class="input-custom-item"
      :class="{'input-custom-placeholder': !localValue?.length, 'inline-text': localValue?.length}"
      tabindex="0"
      @input.stop="handleInput"
      @focus="handleFocus"
      @blur="handleBlur"
      @paste.stop="handleInputPaste"
    >
      {{ content }}
    </span>
  </span>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { handlePaste } from './util';

const emits = defineEmits(['change']);
const props = defineProps({
  content: String,
  placeholder: {
    type: String,
    default: '',
  },
  disabled: {
    type: Boolean,
    default: false,
  },
});

const isEditable = ref(false);
const localValue = ref(props.content);
const editableSpanRef: any = ref(null);

watch(
  () => props.content,
  (newVal) => {
    localValue.value = newVal;
  },
);

const handleFocus = () => {
  isEditable.value = !props.disabled;
};

const handleBlur = () => {
  isEditable.value = false;
};

const handleInput = (e: any) => {
  const prompt = editableSpanRef.value?.textContent || '';
  localValue.value = prompt;
  emits('change', prompt);
};

const handleInputPaste = (e: any) => {
  handlePaste(e);
  handleInput(e);
};
</script>

<style lang="scss" scoped>
@import "devui-theme/styles-var/devui-var.scss";
@import "@matechat/common/Input/common/input-tag.scss";

</style>
