// packages/components/Attachment/drop-area.vue
<template>
  <Teleport to="body">
    <div
      ref="dropAreaEl"
      :class="['mc-attachment-drop-area', !isDragging && 'hide-drop-area']"
      @drop="handleDrop"
    >
      <slot />
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { inject, onBeforeUnmount, onMounted, ref, Teleport, watch } from "vue";
import { AttachmentInjectKey, type IAttachmentCtx } from "./attachment-types";

const { rootProps, rootEmits, isDisabled, uploadFiles } = inject(
  AttachmentInjectKey
) as IAttachmentCtx;

const container = ref<HTMLElement>();
const dropAreaEl = ref<HTMLElement>();
const isDragging = ref(false);
// 使用计数器来跟踪 dragenter 和 dragleave 事件，防止进入子元素导致的状态变化
let dragCounter = 0;

watch(
  () => rootProps.getDropContainer,
  (val) => {
    if (val) {
      const newContainer = val();
      if (container.value !== newContainer) {
        container.value = newContainer;
      }
    }
  }
);

const handleDragEnter = (e: DragEvent) => {
  e.preventDefault();
  dragCounter++;
  if (dragCounter === 1) {
    isDragging.value = true;
  }
  if (container.value && dropAreaEl.value) {
    if (container.value === document.body) {
      dropAreaEl.value.style.inset = "0";
    } else {
      const { x, y, width, height } = container.value.getBoundingClientRect();
      dropAreaEl.value.style.width = `${width}px`;
      dropAreaEl.value.style.height = `${height}px`;
      dropAreaEl.value.style.top = `${y}px`;
      dropAreaEl.value.style.left = `${x}px`;
    }
  }
};
const handleDragOver = (e: DragEvent) => {
  e.preventDefault();
};

const handleDragLeave = (e: DragEvent) => {
  e.preventDefault();
  dragCounter--;
  if (dragCounter === 0) {
    isDragging.value = false;
  }
};

const handleDrop = (e: DragEvent) => {
  e.preventDefault();
  isDragging.value = false;
  dragCounter = 0; // 重置计数器
  if (isDisabled.value) return;

  const files = Array.from(e.dataTransfer?.files || []);
  if (files.length > 0) {
    rootEmits("drop", files);
    uploadFiles(files);
  }
};

function onBodyDrop(e: DragEvent) {
  e.preventDefault();
  isDragging.value = false;
  dragCounter = 0;
}

onMounted(() => {
  if (rootProps.getDropContainer) {
    container.value = rootProps.getDropContainer();
  }
  document.body.addEventListener("dragenter", handleDragEnter);
  document.body.addEventListener("dragover", handleDragOver);
  document.body.addEventListener("dragleave", handleDragLeave);
  document.body.addEventListener("drop", onBodyDrop);
});

onBeforeUnmount(() => {
  document.body.removeEventListener("dragenter", handleDragEnter);
  document.body.removeEventListener("dragover", handleDragOver);
  document.body.removeEventListener("dragleave", handleDragLeave);
  document.body.removeEventListener("drop", onBodyDrop);
});
</script>

<style lang="scss">
@use "@matechat/common/Attachment/common/drop-area.scss";
</style>

// packages/components-ng/projects/components-ng/src/Attachment/drop-area/drop-area.component.ts
import { CommonModule } from '@angular/common';
import {
  type AfterViewInit,
  Component,
  type ElementRef,
  EventEmitter,
  Input,
  type OnDestroy,
  Output,
  type SimpleChanges,
  ViewChild,
} from '@angular/core';

@Component({
  selector: 'mc-drop-area',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './drop-area.component.html',
  styleUrls: ['./drop-area.component.scss'],
})
export class DropAreaComponent implements AfterViewInit, OnDestroy {
  @Input() getDropContainer: () => HTMLElement;
  @Input() isDisabled: boolean = false;
  @Output() drop = new EventEmitter<File[]>();

  @ViewChild('dropArea') dropAreaEl!: ElementRef<HTMLDivElement>;

  container: HTMLElement;
  isDragging = false;
  // 使用计数器来跟踪 dragenter 和 dragleave 事件，防止进入子元素导致的状态变化
  dragCounter = 0;

  ngOnChanges(changes: SimpleChanges) {
    if (changes['getDropContainer'] && this.getDropContainer) {
      const newContainer = this.getDropContainer();
      if (this.container !== newContainer) {
        this.container = newContainer;
      }
    }
  }

  handleDragEnter = (e: DragEvent) => {
    e.preventDefault();
    this.dragCounter++;
    if (this.dragCounter === 1) {
      this.isDragging = true;
    }
    if (this.container && this.dropAreaEl.nativeElement) {
      if (this.container === document.body) {
        this.dropAreaEl.nativeElement.style.inset = '0';
      } else {
        const { x, y, width, height } = this.container.getBoundingClientRect();
        this.dropAreaEl.nativeElement.style.width = `${width}px`;
        this.dropAreaEl.nativeElement.style.height = `${height}px`;
        this.dropAreaEl.nativeElement.style.top = `${y}px`;
        this.dropAreaEl.nativeElement.style.left = `${x}px`;
      }
    }
  };
  handleDragOver = (e: DragEvent) => {
    e.preventDefault();
  };

  handleDragLeave = (e: DragEvent) => {
    e.preventDefault();
    this.dragCounter--;
    if (this.dragCounter === 0) {
      this.isDragging = false;
    }
  };
  handleDrop = (e: DragEvent) => {
    e.preventDefault();
    this.isDragging = false;
    this.dragCounter = 0; // 重置计数器
    if (this.isDisabled) return;

    const files = Array.from(e.dataTransfer?.files || []);
    if (files.length > 0) {
      this.drop.emit(files);
    }
  };
  onBodyDrop = (e: DragEvent) => {
    e.preventDefault();
    this.isDragging = false;
    this.dragCounter = 0;
  };

  ngAfterViewInit(): void {
    document.body.appendChild(this.dropAreaEl.nativeElement);
    if (this.getDropContainer) {
      this.container = this.getDropContainer();
    }
    document.body.addEventListener('dragenter', this.handleDragEnter);
    document.body.addEventListener('dragover', this.handleDragOver);
    document.body.addEventListener('dragleave', this.handleDragLeave);
    document.body.addEventListener('drop', this.onBodyDrop);
  }

  ngOnDestroy(): void {
    document.body.removeEventListener('dragenter', this.handleDragEnter);
    document.body.removeEventListener('dragover', this.handleDragOver);
    document.body.removeEventListener('dragleave', this.handleDragLeave);
    document.body.removeEventListener('drop', this.onBodyDrop);
  }
}

<div
  #dropArea
  [ngClass]="{
    'mc-attachment-drop-area': true,
    'hide-drop-area': !isDragging,
  }"
  (drop)="handleDrop($event)"
>
  <ng-content />
</div>
