// packages/components/Header/Header.vue
<template>
  <div class="mc-header">
    <div class="mc-header-logo-container" :class="{ clickable: logoClickable }" @click="onLogoClicked">
      <img v-if="logoImg" class="mc-header-logo" :src="logoImg" :alt="logoImg" />
      <div class="mc-header-title">{{ title }}</div>
    </div>
    <div class="mc-header-operation">
      <slot name="operationArea"></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { props } from './header-types';

const emits = defineEmits(['logoClicked']);
const headerProps = defineProps(props);

const onLogoClicked = () => {
  if (headerProps.logoClickable) {
    emits('logoClicked');
  }
};
</script>

<style scoped lang="scss">
@use '@matechat/common/Header/common/header.scss';

</style>

// packages/components-ng/projects/components-ng/src/Header/header.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'mc-header',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent {
  @Input() logoImg: string = '';
  @Input() title: string = '';
  @Input() logoClickable: boolean = false;

  @Output() logoClicked = new EventEmitter<void>();

  onLogoClicked(): void {
    if (this.logoClickable) {
      this.logoClicked.emit();
    }
  }
}

<div class="mc-header">
  <div class="mc-header-logo-container" [class]="{ clickable: logoClickable }" (click)="onLogoClicked()">
    <img *ngIf="logoImg" class="mc-header-logo" [src]="logoImg" [alt]="logoImg" />
    <div class="mc-header-title">{{ title }}</div>
  </div>
  <div class="mc-header-operation">
    <ng-content select="[operationArea]"></ng-content>
  </div>
</div>
