// packages/components-ng/projects/components-ng/src/Input/input.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnInit,
  ViewChild,
  ElementRef,
  ContentChild,
  TemplateRef,
  SimpleChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ButtonComponent } from './button/button.component';
import {
  DisplayType,
  InputVariant,
  SendBtnVariant,
  SubmitShortKey,
} from '../components-common/Input/common/types';
import BaseComponent from '../Base/base.component';
import {
  InputAdapter,
  InputFoundation,
} from '../components-common/Input/foundation';
import { LocaleService } from '../components-common/Locale/locale.service';

// 创建一个token用于组件间通信
export const inputContextToken = 'input-context';

@Component({
  selector: 'mc-input',
  standalone: true,
  imports: [CommonModule, FormsModule, ButtonComponent],
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.scss'],
  providers: [{ provide: inputContextToken, useExisting: InputComponent }],
})
export class InputComponent extends BaseComponent implements OnInit {
  @Input() value: string = '';
  @Input() placeholder: string = '';
  @Input() disabled: boolean = false;
  @Input() displayType: DisplayType = DisplayType.Full;
  @Input() variant: InputVariant = InputVariant.Bordered;
  @Input() sendBtnVariant: SendBtnVariant = SendBtnVariant.Full;
  @Input() loading: boolean = false;
  @Input() showCount: boolean = false;
  @Input() maxLength: number | null = null;
  @Input() submitShortKey: SubmitShortKey | null | string =
    SubmitShortKey.Enter;
  @Input() autofocus: boolean = false;

  @Output() change = new EventEmitter<string>();
  @Output() submit = new EventEmitter<string>();
  @Output() cancel = new EventEmitter<void>();
  @Output() focus = new EventEmitter<FocusEvent>();
  @Output() blur = new EventEmitter<FocusEvent>();

  @ViewChild('textarea') textareaElement!: ElementRef<HTMLTextAreaElement>;

  @ContentChild('head') headTemplate: TemplateRef<any> | null = null;
  @ContentChild('prefix') prefixTemplate: TemplateRef<any> | null = null;
  @ContentChild('suffix') suffixTemplate: TemplateRef<any> | null = null;
  @ContentChild('button') buttonTemplate: TemplateRef<any> | null = null;
  @ContentChild('extra') extraTemplate: TemplateRef<any> | null = null;

  inputValue: string = '';
  lock: boolean = false;

  constructor(private localeService: LocaleService) {
    super();
  }

  ngOnInit() {
    this.foundation = new InputFoundation(this.adapter);
    this.foundation.init();
    this.inputValue = this.value;
  }

  override get adapter(): InputAdapter {
    return {
      ...super.adapter,
      locale: (key, params) => this.localeService.translate(key, params),
      emitChange: () => this.change.emit(this.inputValue),
    };
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['value']) {
      this.inputValue = changes['value']?.currentValue || '';
    }
  }

  get inputClasses(): string {
    return this.foundation.getInputClasses();
  }

  get maxlengthValue() {
    return this.maxLength !== undefined ? this.maxLength : null;
  }

  onInput(): void {
    if (!this.lock) {
      this.foundation.emitChange();
    }
  }

  onCompositionStart(): void {
    this.lock = true;
  }

  onCompositionEnd(): void {
    this.lock = false;
    this.foundation.emitChange();
  }

  onKeydown(event: KeyboardEvent): void {
    if (this.submitShortKey === null) {
      return;
    }

    const shiftKey =
      this.submitShortKey === SubmitShortKey.Enter
        ? !event.shiftKey
        : this.submitShortKey === SubmitShortKey.ShiftEnter
        ? event.shiftKey
        : false;

    if (shiftKey && event.key === 'Enter' && !this.lock) {
      event.preventDefault();
      this.submit.emit(this.inputValue);
      this.inputValue = '';
      this.foundation.emitChange();
    }
  }

  clearInput(): void {
    this.foundation.clearInput();
  }

  getInput(): string {
    return this.inputValue;
  }

  // 处理button组件的事件
  onButtonSubmit(value: string): void {
    this.submit.emit(value);
  }

  onButtonCancel(): void {
    this.cancel.emit();
  }

  onButtonChange(value: string): void {
    this.inputValue = value;
    this.foundation.emitChange();
  }

  ngAfterViewInit() {
    if (this.autofocus && this.textareaElement && !this.disabled) {
      // 在下一个变更检测周期中聚焦，以确保视图已经完全初始化
      setTimeout(() => {
        this.textareaElement.nativeElement.focus();
      });
    }
  }

  get placeholderText(): string {
    return this.foundation.getPlaceholderText();
  }

  onFocus(event: FocusEvent) {
    this.focus.emit(event);
  }

  onBlur(event: FocusEvent) {
    this.blur.emit(event);
  }
}

<div [ngClass]="inputClasses">
  <ng-container *ngIf="headTemplate; then headTemplate"></ng-container>

  <div class="mc-input-content">
    <ng-container *ngIf="prefixTemplate; then prefixTemplate"></ng-container>
    <!-- 替换Textarea -->
    <div *ngIf="showEditableBlock" class="editable-block-container">
      <mc-editable-block *ngIf="showEditableBlock"
        #editableBlock
        [placeholder]="placeholder"
        [maxLength]="maxLength"
        [disabled]="disabled"
        [submitShortKey]="submitShortKey"
        [autofocus]="autofocus"
        (input)="handleDivInput($event)"
        (send)="handleDivSubmit($event)"
        (blur)="onDivBlur($event)"
        (focus)="onDivFocus($event)"
      >
        <ng-template #themeTag let-themeTagText="themeTagText">
          <!-- 需要解决ng模板值的传递 -->
           <ng-container *ngIf="themeTagTemplate">
            <ng-container *ngTemplateOutlet="themeTagTemplate; context: {$implicit: themeTagText, themeTagText: themeTagText}"></ng-container>
           </ng-container>
          
        </ng-template>
      </mc-editable-block>
    </div>
    <textarea
      *ngIf="!showEditableBlock"
      #textarea
      [(ngModel)]="inputValue"
      [placeholder]="placeholderText"
      [disabled]="disabled"
      [maxlength]="maxLength"
      class="mc-textarea"
      [ngClass]="{
        'mc-textarea-simple': displayType === 'simple',
        'mc-textarea-disabled': disabled
      }"
      [ngStyle]="textareaStyle"
      [attr.aria-label]="'Input.ariaLabel' | translate"
      [attr.aria-disabled]="disabled"
      (input)="onInput()"
      (change)="onChange($event)"
      (compositionstart)="onCompositionStart()"
      (compositionend)="onCompositionEnd()"
      (keydown)="onKeydown($event)"
      (focus)="onFocus($event)"
      (blur)="onBlur($event)"
    ></textarea>
    <ng-container *ngIf="suffixTemplate; then suffixTemplate"></ng-container>

    <ng-container *ngIf="displayType === 'simple'">
      <ng-container *ngIf="buttonTemplate; else defaultButton">
        <ng-container
          *ngIf="buttonTemplate; then buttonTemplate"
        ></ng-container>
      </ng-container>
      <ng-template #defaultButton>
        <mc-button
          [disabled]="disabled || (!loading && !inputValue)"
          [loading]="loading"
          [inputValue]="inputValue"
          [sendBtnVariant]="sendBtnVariant"
          (submit)="onButtonSubmit($event)"
          (cancel)="onButtonCancel()"
          (change)="onButtonChange($event)"
        ></mc-button>
      </ng-template>
    </ng-container>
  </div>

  <div *ngIf="displayType === 'full'" class="mc-input-foot">
    <div class="mc-input-foot-left">
      <ng-container *ngIf="extraTemplate; then extraTemplate"></ng-container>
      <span *ngIf="showCount" id="mc-input-count" class="mc-input-foot-count">
        {{ inputValue.length }}{{ !maxLength ? "" : "/" + maxLength }}
      </span>
    </div>

    <ng-container *ngIf="buttonTemplate; else defaultFooterButton">
      <ng-container *ngIf="buttonTemplate; then buttonTemplate"></ng-container>
    </ng-container>
    <ng-template #defaultFooterButton>
      <mc-button
        [disabled]="disabled || (!loading && !inputValue)"
        [loading]="loading"
        [inputValue]="inputValue"
        [sendBtnVariant]="sendBtnVariant"
        (submit)="onButtonSubmit($event)"
        (cancel)="onButtonCancel()"
        (change)="onButtonChange($event)"
      ></mc-button>
    </ng-template>
  </div>
</div>

// packages/components/Input/Input.vue
<template>
  <div :class="inputClasses">
    <slot name="head" />
    <div class="mc-input-content">
      <slot name="prefix" />
      <!-- 替换Textarea -->
      <div v-if="showEditableBlock" class="editable-block-container">
        <!-- 可编辑块 -->
         <EditableBlock v-if="showEditableBlock"
          ref="editableBlockRef"
          :placeholder="props.placeholder"
          :maxLength="props.maxLength"
          :disabled="props.disabled"
          :submit-short-key="props.submitShortKey"
          :autofocus="props.autofocus"
          @input="handleDivInput"
          @send="handleDivSubmit"
          @blur="onDivBlur"
          @focus="onDivFocus"
         >
          <template #tipTagIcon>
            <slot name="tipTagIcon" ></slot>
          </template>
         </EditableBlock>
      </div>
      <Textarea v-if="!showEditableBlock"/>
      <slot name="suffix" />
      <slot v-if="displayType === DisplayType.Simple" name="button">
        <Button />
      </slot>
    </div>
    <div v-if="displayType === DisplayType.Full" class="mc-input-foot">
      <div class="mc-input-foot-left">
        <slot name="extra" />
        <span v-if="showCount" class="mc-input-foot-count">
          {{ inputValue.length
          }}{{ !(maxLength ?? false) ? "" : `/${maxLength}` }}
        </span>
      </div>
      <slot name="button">
        <Button />
      </slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, provide, computed } from "vue";
import Textarea from "./components/textarea.vue";
import EditableBlock from "./components/EditableBlock.vue";
import Button from "./components/button.vue";
import {
  inputProps,
  inputEmits,
  inputInjectionKey,
  DisplayType,
  InputVariant,
  MixTagItem,
} from "./input-types";

const props = defineProps(inputProps);
const emits = defineEmits(inputEmits);
const editableBlockRef:any = ref(null);
const showEditableBlock = ref(false);
const inputValue = ref("");
const inputClasses = computed(() => ({
  "mc-input": true,
  "mc-input-disabled": props.disabled,
  "mc-input-simple": props.displayType === DisplayType.Simple,
  "mc-input-borderless": props.variant === InputVariant.BorderLess,
}));

const clearInput = () => {
  if(showEditableBlock.value) {
    editableBlockRef.value?.clearInput();
  }else{
    inputValue.value = "";
  }
};

const clearInputAfterSubmit = () => {
  if (props.autoClear) {
    clearInput();
  }
};
const getInput = () => {
  if(showEditableBlock.value) {
    return editableBlockRef.value?.getInput();
  }
  return inputValue.value;
}

const setInputTag = (key: string, placeholder: string, defaultValue?:string) => {
  if(props.disabled) {
    return;
  }
  showEditableBlock.value = true;
  setTimeout(() => {
    editableBlockRef.value?.setInputTag(key, placeholder, defaultValue);
  }, 50);
}

const setText = (text: string) => {
  if(props.disabled) {
    return;
  }
  showEditableBlock.value = true;
  setTimeout(() => {
    editableBlockRef.value?.setText(text);
  }, 50);
  
}

const setMixTags = (mixTagConfig: MixTagItem[]) => {
  if(props.disabled) {
    return;
  }
  showEditableBlock.value = true;
  setTimeout(() => {
    editableBlockRef.value?.setMixTags(mixTagConfig);
  }, 50);
}

const openTipTag = (tipTagText: string, clearInput?: boolean) => {
  if(props.disabled) {
    return;
  }
  showEditableBlock.value = true;
  setTimeout(() => {
    editableBlockRef.value?.openTipTag(tipTagText, clearInput);
  }, 50);
}

const closeTipTag = () => {
  if(showEditableBlock.value) {
    editableBlockRef.value?.closeTipTag();
  }
}

const handleDivInput = (value: string) => {
  if(!value) {
    setTimeout(() => {
      showEditableBlock.value = false;
    }, 50);
  }
  inputValue.value = value;
  emits('change', value);
}

const handleDivSubmit = (value: string) => {
  emits('submit', value);
}

const onDivBlur = (e: FocusEvent) => {
  emits('blur', e);
}

const onDivFocus = (e: FocusEvent) => {
  emits('focus', e);
}

watch(
  () => props.value,
  () => {
    inputValue.value = props.value;
  },
  { immediate: true }
);

defineExpose({ clearInput, getInput, setInputTag, setText, setMixTags, openTipTag, closeTipTag });
provide(inputInjectionKey, { inputValue, rootProps: props, rootEmits: emits, clearInputAfterSubmit });
</script>

<style lang="scss">
@import "./input.scss";
</style>
